"""
Django settings for rapide project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
from .base import *

FEDAPAY_SECRET_KEY = config("PRIV")
FEDAPAY_PUBLIC_KEY = config("PUB")
FEDAPAY_API_BASE = "https://sandbox-api.fedapay.com/v1"
WEBHOOK = config("WEBHOOK")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m$m-1v)(i2=er7r+(82#k5m+9&t^@zp0#3z^q1j$12h$5ndti='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["http://localhost:5173/", '127.0.0.1', "localhost", "bespoke-frontend-3xui.onrender.com"]

AUTH_USER_MODEL = "partner.User"

# ~ STATICFILES_DIR =  
# Application definition
 
# Session settings
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # or 'cache' or 'file'
SESSION_COOKIE_NAME = 'sessionid'
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_SAMESITE = "None"
SESSION_COOKIE_HTTP_ONLY = True


# For development, you might need to disable secure cookies
SESSION_COOKIE_SECURE = True  # True in production with HTTPS
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = "None" 

WSGI_APPLICATION = 'rapide.wsgi.application'

CORS_ALLOWED_ORIGINS = [
     "http://localhost:3000",
    "http://localhost:5173",  # Vite default port
    "http://127.0.0.1:5173",
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    
]

# Allow credentials (cookies, auth headers)
CORS_ALLOW_CREDENTIALS = True

# Allow specific headers
CORS_ALLOW_HEADERS = [
    'content-type',
    'authorization',
    'x-csrftoken',
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
]

CSRF_COOKIE_SAMESITE = "Lax"

LOGIN_URL = "/api/login/"

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
