"""
Django settings for rapide project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
from .base import *


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


FEDAPAY_SECRET_KEY = config("PRIV")
FEDAPAY_PUBLIC_KEY = config("PUB")
FEDAPAY_API_BASE = "https://sandbox-api.fedapay.com/v1"
WEBHOOK = config("WEBHOOK")
 

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m$m-1v)(i2=er7r+(82#k5m+9&t^@zp0#3z^q1j$12h$5ndti='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["bespoke-backend-zzmu.onrender.com", "bespoke-frontend-3xui.onrender.com"]

ROOT_URLCONF = 'rapide.urls'
# Session settings
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # or 'cache' or 'file'
SESSION_COOKIE_NAME = 'sessionid'
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_SAMESITE = "None"
SESSION_COOKIE_HTTP_ONLY = True
SESSION_COOKIE_SECURE = True  # True in production with HTTPS

CSRF_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = "None" 
CSRF_TRUSTED_ORIGINS = ["https://bespoke-frontend-tuzj.onrender.com", "https://bespoke-frontend-3xui.onrender.com"]
CSRF_COOKIE_HTTPONLY = False

WSGI_APPLICATION = 'rapide.wsgi.application'

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
CORS_ALLOWED_ORIGINS = [
    "https://bespoke-frontend-tuzj.onrender.com",
    "https://bespoke-frontend-3xui.onrender.com",
]

# Allow credentials (cookies, auth headers)
CORS_ALLOW_CREDENTIALS = True

# Allow specific headers
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
